Determine CPU info for ARM processors
DataDog/gohai pull request #109
Opened 2022-07-08 18:51 UTC by djmitche

This is loosely based on lscpu, and organizes the data to fit the
existing field defintiions and formats.

It seems that `/proc/cpuinfo` contains lots of useful detail for x86 architectures, but very little for ARM, so this fetches data from various /sys files instead, as lscpu does.

Note that CI doesn't cover ARM.  I'm not sure of an easy way to fix that!

2022-07-08 18:53 UTC, djmitche commented
It'd be great if someone could run this on a rPi.

2022-07-11 13:08 UTC, hush-hush requested changes

2022-07-11 13:08 UTC, hush-hush commented on cpu/cpu_linux_arm64.go
> +// See from-lscpu-arm.py to regenerate this value.
Should we isolate this in its own file that the python script can overwrite ?

2022-07-11 13:08 UTC, hush-hush commented on cpu/from-lscpu-arm.py
> +#! /usr/bin/env python
Could we add something to the README about how to use this and when to update the ARM cpu definition ?

2022-07-11 16:19 UTC, hush-hush approved these changes
On nit on the README but looks good otherwise

2022-07-11 19:10 UTC, sgnn7 approved these changes
@djmitche LGTM just a couple of nits

2022-07-11 19:26 UTC, djmitche commented on cpu/util_linux.go
> +	file, err := os.Open(testingPrefix + "/proc/cpuinfo")
What non-testing context are you seeing it in?

2022-07-11 19:38 UTC, djmitche commented
That should fix the CPU issue -- can you test again?

2022-07-11 19:38 UTC, djmitche commented
(and, it seems that Linux does not know the cache sizes on rPi, so that's the best we can do)

2022-07-11 19:46 UTC, sgnn7 commented on cpu/util_linux.go
> +	file, err := os.Open(testingPrefix + "/proc/cpuinfo")
The same code is run when you regularly build the `gohai` executable or import this as a module. The `testing` prefix on this var is much less fitting for those contexts.

2022-07-11 20:42 UTC, sgnn7 commented
@djmitche Looks good!

```json
{
  "cache_size": "0 KB",
  "cache_size_l1": "0",
  "cache_size_l2": "0",
  "cache_size_l3": "0",
  "cpu_cores": "4",
  "cpu_logical_processors": "4",
  "cpu_numa_nodes": "0",
  "cpu_pkgs": "1",
  "family": "none",
  "model": "0xd08",
  "model_name": "Cortex-A72",
  "stepping": "r0p3",
  "vendor_id": "ARM"
}
```

2022-07-11 20:46 UTC, sgnn7 approved these changes

2022-07-11 20:48 UTC, merged